# Generated by Django 6.0.5 on 2026-05-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=100, unique=True)),
                ('matricule_entreprise', models.CharField(max_length=50, unique=True)),
                ('date_debut_contrat', models.DateField()),
                ('date_fin_contrat', models.DateField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('code_assurance', models.CharField(max_length=20, unique=True)),
                ('taux_couverture', models.IntegerField(help_text="Pourcentage pris en charge par l'assurance (ex: 80 pour 80%)")),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgl_id', models.CharField(help_text="Identifiant unique du patient à l'hôpital", max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('numero_assure', models.CharField(blank=True, help_text="Numéro de carte d'assurance", max_length=50, null=True)),
                ('abonne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes_patients', to='admission.abonne')),
                ('assurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='admission.assurance')),
            ],
        ),
    ]
