# Generated by Django 6.0.5 on 2026-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_patient_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nombre_enfants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_identite',
            field=models.CharField(blank=True, help_text="N° carte d'identité nationale", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='poids_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='situation_familiale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='taille_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
