# Generated by Django 6.0.5 on 2026-06-21 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_patient_nombre_enfants_patient_numero_identite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPrivilegie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(max_length=30, unique=True)),
                ('type_carte', models.CharField(choices=[('VIP', 'Carte VIP'), ('OR', 'Carte Or'), ('PREMIUM', 'Carte Premium'), ('FAMILLE', 'Carte Famille')], default='VIP', max_length=15)),
                ('taux_reduction', models.IntegerField(default=10, help_text='Pourcentage de réduction (ex: 15 pour 15%)')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privilege', to='admission.patient')),
            ],
            options={
                'verbose_name': 'Client privilégié',
                'verbose_name_plural': 'Clients privilégiés',
            },
        ),
    ]
