# Generated by Django 6.0.1 on 2026-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Allergies connues', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, help_text='Antécédents médicaux détaillés', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_lien',
            field=models.CharField(blank=True, help_text='Parent, conjoint, ami…', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
