# Generated by Django 6.0.5 on 2026-07-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0009_patient_allergies_patient_antecedents_medicaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_role', models.CharField(default='PATIENT', max_length=30)),
                ('message_type', models.CharField(choices=[('CHAT', 'Message'), ('RDV_DEMANDE', 'Demande de rendez-vous'), ('RDV_CONFIRME', 'Confirmation rendez-vous'), ('SYSTEM', 'Système')], default='CHAT', max_length=20)),
                ('contenu', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lu_par_patient', models.BooleanField(default=False)),
                ('lu_par_equipe', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat', to='admission.patient')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_chat', to='admission.rendezvous')),
            ],
            options={
                'verbose_name': 'Message chat patient',
                'verbose_name_plural': 'Messages chat patients',
                'ordering': ['created_at'],
            },
        ),
    ]
