# Generated by Django 6.0.5 on 2026-05-24 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('type_chambre', models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('REANIMATION', 'Réanimation')], default='STANDARD', max_length=20)),
                ('prix_journalier', models.DecimalField(decimal_places=2, help_text="Prix par jour d'hospitalisation", max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lit', models.CharField(max_length=10)),
                ('est_occupe', models.BooleanField(default=False)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='clinical.chambre')),
            ],
            options={
                'unique_together': {('chambre', 'code_lit')},
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif_hospitalisation', models.TextField()),
                ('est_cloture', models.BooleanField(default=False)),
                ('frais_hebergement_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisations', to='admission.patient')),
                ('lit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='clinical.lit')),
            ],
        ),
    ]
