# Generated by Django 6.0.5 on 2026-06-20 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_patient_user'),
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BanqueSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('numero_poche', models.CharField(max_length=30, unique=True)),
                ('volume_ml', models.IntegerField(default=450)),
                ('date_collecte', models.DateField()),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('CRITIQUE', 'Stock critique'), ('EXPIRE', 'Expiré')], default='DISPONIBLE', max_length=15)),
                ('donneur_id', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Poche de sang',
                'verbose_name_plural': 'Banque de sang',
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='batiment',
            field=models.CharField(default='Bâtiment A', max_length=50),
        ),
        migrations.AddField(
            model_name='chambre',
            name='etage',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('batiment', models.CharField(default='Bâtiment A', max_length=50)),
                ('etage', models.CharField(default='RDC', max_length=10)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('secretaire', models.ForeignKey(blank=True, limit_choices_to={'role': 'SECRETAIRE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='LocalisationPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.CharField(default='Bâtiment A', max_length=50)),
                ('etage', models.CharField(default='RDC', max_length=10)),
                ('salle', models.CharField(default='Accueil', max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('statut', models.CharField(choices=[('ENREGISTRE', "Enregistré à l'accueil"), ('EN_ATTENTE', "En salle d'attente"), ('EN_CONSULTATION', 'En consultation'), ('EXAMEN', 'En examen'), ('HOSPITALISE', 'Hospitalisé'), ('SORTI', 'Sorti')], default='ENREGISTRE', max_length=20)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='admission.patient')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_presents', to='clinical.service')),
            ],
            options={
                'verbose_name': 'Localisation patient',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
        migrations.AddField(
            model_name='chambre',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chambres', to='clinical.service'),
        ),
    ]
