# Generated by Django 6.0.5 on 2026-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_banquesang_chambre_batiment_chambre_etage_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPEE', 'Occupée'), ('NETTOYAGE', 'En nettoyage'), ('MAINTENANCE', 'En maintenance')], default='LIBRE', max_length=15),
        ),
    ]
