# Generated by Django 6.0.1 on 2026-06-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_service_en_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='salleattente',
            name='type_file',
            field=models.CharField(choices=[('STANDARD', 'Salle standard'), ('PRIVILEGE', 'Salle VIP privilèges')], default='STANDARD', help_text='File standard ou salon réservé aux clients privilégiés', max_length=15),
        ),
    ]
