# Generated by Django 6.0.5 on 2026-06-20 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_banquesang_chambre_batiment_chambre_etage_service_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='clinical.service'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('SECRETAIRE', 'Secrétaire'), ('RECEPTIONNISTE', 'Réceptionniste'), ('BIOLOGISTE', 'Biologiste'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
