# Generated by Django 6.0.5 on 2026-06-21 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_chambre_statut'),
        ('users', '0003_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('Cardiologie', 'Cardiologie'), ('Neurologie', 'Neurologie'), ('Pédiatrie', 'Pédiatrie'), ('Gynécologie', 'Gynécologie'), ('Dermatologie', 'Dermatologie'), ('Orthopédie', 'Orthopédie'), ('Psychiatrie', 'Psychiatrie'), ('Ophtalmologie', 'Ophtalmologie'), ('Urgences', 'Urgences'), ('Médecine générale', 'Médecine générale')], default='Médecine générale', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, default='')),
                ('numero_ordre', models.CharField(blank=True, default='', help_text='N° ordre des médecins', max_length=30)),
                ('photo', models.URLField(blank=True, default='')),
                ('est_actif', models.BooleanField(default=True)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medecins', to='clinical.service')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_medecin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
