# Generated by Django 6.0.1 on 2026-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_secretaire_generale_docteur_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('SECRETAIRE_GENERALE', 'Secrétaire générale'), ('MEDECIN', 'Médecin'), ('INFIRMIER', 'Infirmier'), ('SECRETAIRE', 'Secrétaire'), ('RECEPTIONNISTE', 'Réceptionniste'), ('BIOLOGISTE', 'Biologiste / Laborantin'), ('PHARMACIEN', 'Pharmacien'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
