# Generated by Django 6.0.5 on 2026-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='channel',
            field=models.CharField(default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
