# Generated by Django 6.0.5 on 2026-05-24 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('montant_consultations', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_laboratoire', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_hospitalisation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_pharmacie', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_total_brut', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('part_assurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('montant_patient_net', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PAYE', 'Payée'), ('PARTIEL', 'Paiement Partiel')], default='EN_ATTENTE', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='admission.patient')),
            ],
        ),
    ]
