# Generated by Django 6.0.5 on 2026-07-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsettings',
            name='config_style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='icone_application',
            field=models.CharField(default='🏥', max_length=10),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='nom_application',
            field=models.CharField(default='SGHL', max_length=80),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='slogan_application',
            field=models.CharField(default='Système de Gestion Hospitalière et de Laboratoire', max_length=200),
        ),
        migrations.AddField(
            model_name='hospitalsettings',
            name='theme_ui',
            field=models.CharField(default='teal', max_length=30),
        ),
    ]
