# Generated by Django 6.0.5 on 2026-05-17 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_nom', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('COMMANDE', 'Commande'), ('PRELEVEMENT', 'Prélèvement'), ('SAISIE', 'Saisie'), ('VALIDE', 'Validé')], default='COMMANDE', max_length=20)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('est_immuable', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
