# Generated by Django 6.0.5 on 2026-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='statut',
            field=models.CharField(choices=[('COMMANDE', 'Commande'), ('PRELEVEMENT', 'Prelevement'), ('SAISIE', 'Saisie'), ('VALIDE', 'Valide')], default='COMMANDE', max_length=20),
        ),
    ]
