# Generated by Django 6.0.5 on 2026-06-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_patient_groupe_sanguin_and_more'),
        ('laboratory', '0002_alter_analyse_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='patient_dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='admission.patient'),
        ),
    ]
