# Generated by Django 6.0.5 on 2026-05-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('code_barre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantite_en_stock', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix de vente d'une boîte/unité", max_digits=10)),
                ('date_expiration', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionPharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_delivree', models.IntegerField()),
                ('frais_pharmacie_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date_dispensation', models.DateTimeField(auto_now_add=True)),
                ('est_paye', models.BooleanField(default=False)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='pharmacy.medicament')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achats_pharmacie', to='admission.patient')),
            ],
        ),
    ]
