# Generated by Django 6.0.5 on 2026-05-24 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_arterielle', models.CharField(blank=True, help_text='Ex: 12/8', max_length=20, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='En °C', max_digits=4, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, help_text='En kg', max_digits=5, null=True)),
                ('pouls', models.IntegerField(blank=True, help_text='Battements par minute', null=True)),
                ('motif_consultation', models.TextField()),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('notes_medicales', models.TextField(blank=True, null=True)),
                ('frais_consultation', models.DecimalField(decimal_places=2, default=10000.0, help_text="Coût brut de l'acte médical", max_digits=10)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_effectuees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='admission.patient')),
            ],
        ),
    ]
